id: A3C6CBC65
title: 'The Song of Devotion: Verses of Aspiration for the Fulfilment of the Enlightened
  Vision of Khenchen Jigme Phuntsok, the Reincarnation of Terton Lerab Lingpa'
type: translation
pechas:
- I014B14C1
- IC5E210CC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:25.867924
  last_modified_at: 2023-01-04 12:49:25.867943
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I014B14C1/9FB3: A6F5
  IC5E210CC/A635: A6F5
